#!/bin/sh

######################################################
##             SHORK UTILITY - SHORKDIR             ##
######################################################
## Bootstrap script for shorkdir                    ##
######################################################
## Licence: GNU GENERAL PUBLIC LICENSE Version 3    ##
######################################################
## Kali (links.sharktastica.co.uk)                  ##
######################################################

"$PWD/shorkdir-exec" || exit 1
tmp="/tmp/shorkdir_last_dir.txt"
if [ -f "$tmp" ]; then
    dir=$(cat $tmp)
    rm -f "$tmp"

    if [ -d "$dir" ]; then
        cd "$dir"
        exec $SHELL
    fi
fi
